### ISSUE TITLE
Make this rat public 

### ISSUE THREAD

**Issue by swagkarna** [adhiraj-ranjan/androidRat#1]
Whether it is tcp/php based rat And what are all the features

**Comment by adhiraj-ranjan** [comment]
this Android rat is not going to be public

**Comment by swagkarna** [comment]
Then y did u upload to github if it is private u want to sell this rat in github

**Comment by adhiraj-ranjan** [comment]
i uploaded here to transfer the files easily to my other devices....

Hey but you are talking about selling, Can i sell the rat, Will anyone would buy?
I made it for personal uses, If i made it public , It will soon be easily detectable by AVs....This is the reason i m not making it public

**Comment by swagkarna** [comment]
yes there are more chances that people buy these types of rat also you say its fud then they surely gonna buy just give a try

**Comment by swagkarna** [comment]
![Screenshot (180)](https://user-images.githubusercontent.com/46685308/122925130-28e25f00-d384-11eb-94f0-6fa66411e57c.png)
Hey man i test your rat on my **nox palyer** it works cool.But you should make this rat public so as other too get benefit also u get stars and love from skids also u can improve..If you dont make this project public and if u dont add proper instruction on how to  use this rat then i will post this rat on my github page with proper explanation and with some additional features and video tutorials...Also i wont give you any credits its better u take your credits nor i will take

**Comment by swagkarna** [comment]
![Uploading Screenshot (181).png…]()

**Comment by swagkarna** [comment]
![Screenshot (181)](https://user-images.githubusercontent.com/46685308/122928271-51b82380-d387-11eb-87ea-9f00d1df3011.png)

**Comment by adhiraj-ranjan** [comment]
Hey, I want to talk to you personally...Any of your social sites ID?

**Comment by swagkarna** [comment]
see your instagram

**Comment by swagkarna** [comment]
> You shoudn't upload that to virus total...😡
> 
> Hey, I want to talk to you personally...Any of your social sites ID?

Hey man you have uploaded the apk file to github so dont expect your apk will be fud for long time also u should have made your repo private if u really care of fud now its signature will be shared to av company so now u can freely make it public
